name       : yelp
version    : 3.22.0
release    : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/yelp/3.22/yelp-3.22.0.tar.xz : 8616b77c239aaa731312609f192c9b2c71d54b2cae42ff23efa23b5b3188778e
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME Help Browser
description: |
    Yelp is the default help browser for the GNOME desktop.  Yelp provides
    a simple graphical interface for viewing DocBook, HTML, man, and info
    formatted documentation.  The name Yelp was suggested by Daniel Lundin.
    Yelp is pronounced the same as the swedish word for 'help'.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-web-extension-4.0)
    - pkgconfig(yelp-xsl)
    - itstool
rundeps    :
    - docbook-xml
    - gnome-doc-utils
    - yelp-xsl
setup      : |
    %configure --disable-static \
               --enable-lzma \
               --enable-bz2
build      : |
    %make
install    : |
    %make_install
