name       : yelp
version    : 3.20.1
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/yelp/3.20/yelp-3.20.1.tar.xz : dda0b051ad32908cb9d894d1db3ffdac69b21849b8a6a9a74d9669b017f608c2
license    : GPL-2.0
summary    : GNOME Help Browser
description: |
    Yelp is the default help browser for the GNOME desktop.  Yelp provides
    a simple graphical interface for viewing DocBook, HTML, man, and info
    formatted documentation.  The name Yelp was suggested by Daniel Lundin.
    Yelp is pronounced the same as the swedish word for 'help'.
builddeps  :
    - pkgconfig(webkit2gtk-web-extension-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(yelp-xsl)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - itstool
rundeps    :
    - docbook-xml
    - gnome-doc-utils
    - yelp-xsl
setup      : |
    %configure --disable-static \
               --enable-lzma \
               --enable-bz2
build      : |
    %make
install    : |
    %make_install
