name       : yelp
version    : 3.26.0
release    : 6
source     :
    - https://download.gnome.org/sources/yelp/3.26/yelp-3.26.0.tar.xz : e4cb02ed2f44cfec3c352c957f8a461d9689cbc06eb3b503a58ffe92e1753f1b
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME Help Browser
description: |
    Yelp is the default help browser for the GNOME desktop.  Yelp provides
    a simple graphical interface for viewing DocBook, HTML, man, and info
    formatted documentation.  The name Yelp was suggested by Daniel Lundin.
    Yelp is pronounced the same as the swedish word for 'help'.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-web-extension-4.0)
    - pkgconfig(yelp-xsl)
    - bzip2-devel
    - itstool
rundeps    :
    - docbook-xml
    - gnome-doc-utils
    - yelp-xsl
setup      : |
    %configure --disable-static \
               --enable-lzma \
               --enable-bz2
build      : |
    %make
install    : |
    %make_install
