name       : yelp
version    : '41.2'
release    : 22
source     :
    - https://download.gnome.org/sources/yelp/41/yelp-41.2.tar.xz : b00bf033f02dd79b6d3f255031c71df8d6ed38e552c870b8f391a374724c43c5
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Help Browser
description: |
    Yelp is the default help browser for the GNOME desktop.  Yelp provides
    a simple graphical interface for viewing DocBook, HTML, man, and info
    formatted documentation.  The name Yelp was suggested by Daniel Lundin.
    Yelp is pronounced the same as the swedish word for 'help'.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-web-extension-4.0)
    - pkgconfig(yelp-xsl)
    - bzip2-devel
    - itstool
    - libgcrypt-devel
rundeps    :
    - docbook-xml
    - gnome-doc-utils
    - yelp-xsl
setup      : |
    %configure --disable-static \
               --enable-lzma \
               --enable-bz2 \
               --with-webkit2gtk-4-0
build      : |
    %make
install    : |
    %make_install
