name       : yelp
version    : '40.0'
release    : 16
source     :
    - https://download.gnome.org/sources/yelp/40/yelp-40.0.tar.xz : 07775fa06cd28365ecd829bb16a85a682897ab21d8cce34596bbef5cd455aae0
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Help Browser
description: |
    Yelp is the default help browser for the GNOME desktop.  Yelp provides
    a simple graphical interface for viewing DocBook, HTML, man, and info
    formatted documentation.  The name Yelp was suggested by Daniel Lundin.
    Yelp is pronounced the same as the swedish word for 'help'.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-web-extension-4.0)
    - pkgconfig(yelp-xsl)
    - bzip2-devel
    - itstool
    - libgcrypt-devel
rundeps    :
    - docbook-xml
    - gnome-doc-utils
    - yelp-xsl
setup      : |
    %configure --disable-static \
               --enable-lzma \
               --enable-bz2
build      : |
    %make
install    : |
    %make_install
